#!/bin/sh

# Dependencies: pipewire-jack scx-scheds
# Optional Dependcies: kdialog zenity

## KDialog Prompts

kde_cpu_menu() {
    CPU_CONFIG_MENU=`kdialog --combobox "Scxctl CPU configuration" "Start" "Switch" "Stop"`
}

kde_main_menu() {
    MAIN_MENU=`kdialog --combobox "Archlinux multimedia control center" "Scxctl" "Pipewire" "Exit"`
}

kde_pipewire_session() {
    AUDIO_BUFFER=`kdialog --combobox "Select an audio buffer" "default" "16" "24" "32" "48" "64" "96" "128" "192" "256" "384" "512" "768" "1024" "2048" "4096" "8192"`
    AUDIO_SAMPLE_RATE=`kdialog --combobox "Select a samplerate" "default" "44100" "48000" "88200" "96000" "192000"`
}

kde_scheduler_menu() {
    SCHEDULER_COICE=`kdialog --combobox "CPU schedulers" "bpfland" "flash" "lavd" "p2dq" "tickless" "rusty"`
    MODE_CHOICE=`kdialog --combobox "Scxctl CPU profile" "auto" "gaming" "powersave" "lowlatency" "server"`
}

## Zenity Prompts

zenity_cpu_menu() {
    CPU_CONFIG_MENU=`zenity --list --title="Scxctl CPU configuration" --column="Options" "Start" "Switch" "Stop"`
}

zenity_main_menu() {
    MAIN_MENU=`zenity --list --title="Archlinux multimedia control center" --column="Options" "Scxctl" "Pipewire" "Exit"`
}

zenity_pipewire_session() {
    AUDIO_BUFFER=`zenity --list --title="Select an audio buffer" --column="Options" "default" "16" "24" "32" "48" "64" "96" "128" "192" "256" "384" "512" "768" "1024" "2048" "4096" "8192"`
    AUDIO_SAMPLE_RATE=`zenity --list --title="Select a samplerate" --column="Options" "default" "44100" "48000" "88200" "96000" "192000"`
}

zenity_scheduler_menu() {
    SCHEDULER_COICE=`zenity --list --title="CPU schedulers" --column="Options" "bpfland" "flash" "lavd" "p2dq" "tickless" "rusty"`
    MODE_CHOICE=`zenity --list --title="Scxctl CPU profile" --column="Options" "auto" "gaming" "powersave" "lowlatency" "server"`
}

## Program Logic

cpu_sched_start() {
    scxctl start --sched ${SCHEDULER_COICE} --mode ${MODE_CHOICE}
}

cpu_sched_switch() {
    scxctl switch --sched ${SCHEDULER_COICE} --mode ${MODE_CHOICE}
}

pw_session_logic() {
    # Set audio buffer period
    case $AUDIO_BUFFER in
        default)
            pw-metadata -n settings 0 clock.force-quantum 0 > /dev/null
            ;;

        16)
            pw-metadata -n settings 0 clock.force-quantum 16 > /dev/null
            ;;

        24)
            pw-metadata -n settings 0 clock.force-quantum 24 > /dev/null
            ;;

        32)
            pw-metadata -n settings 0 clock.force-quantum 32 > /dev/null
            ;;

        48)
            pw-metadata -n settings 0 clock.force-quantum 48 > /dev/null
            ;;

        64)
            pw-metadata -n settings 0 clock.force-quantum 64 > /dev/null
            ;;

        96)
            pw-metadata -n settings 0 clock.force-quantum 96 > /dev/null
            ;;

        128)
            pw-metadata -n settings 0 clock.force-quantum 128 > /dev/null
            ;;

        192)
            pw-metadata -n settings 0 clock.force-quantum 192 > /dev/null
            ;;

        256)
            pw-metadata -n settings 0 clock.force-quantum 256 > /dev/null
            ;;

        384)
            pw-metadata -n settings 0 clock.force-quantum 384 > /dev/null
            ;;

        512)
            pw-metadata -n settings 0 clock.force-quantum 512 > /dev/null
            ;;

        768)
            pw-metadata -n settings 0 clock.force-quantum 768 > /dev/null
            ;;

        1024)
            pw-metadata -n settings 0 clock.force-quantum 1024 > /dev/null
            ;;

        2048)
            pw-metadata -n settings 0 clock.force-quantum 2048 > /dev/null
            ;;

        4096)
            pw-metadata -n settings 0 clock.force-quantum 4096 > /dev/null
            ;;

        8192)
            pw-metadata -n settings 0 clock.force-quantum 8192 > /dev/null
            ;;

        *)
            unset $AUDIO_BUFFER
            ;;
    esac

    # Set audio samplerate for pipewire
    case $AUDIO_SAMPLE_RATE in
        default)
            pw-metadata -n settings 0 clock.force-rate 0 > /dev/null
            ;;

        44100)
            pw-metadata -n settings 0 clock.force-rate 44100 > /dev/null
            ;;

        48000)
            pw-metadata -n settings 0 clock.force-rate 48000 > /dev/null
            ;;

        88200)
            pw-metadata -n settings 0 clock.force-rate 88200 > /dev/null
            ;;

        96000)
            pw-metadata -n settings 0 clock.force-rate 96000 > /dev/null
            ;;

        192000)
            pw-metadata -n settings 0 clock.force-rate 192000 > /dev/null
            ;;

        *)
            unset $AUDIO_SAMPLE_RATE
            ;;
    esac
}

## Session Tray Output

pw_session_systray() {
    # Display a notification
    if [[ ! -z "$AUDIO_BUFFER" ]] && [[ ! -z "$AUDIO_SAMPLE_RATE" ]]; then
        kdialog --title "Pipweire settings changed" --passivepopup "Set the pipewire audio buffer period to \"$AUDIO_BUFFER\" and audio samplerate to \"$AUDIO_SAMPLE_RATE\"." 10
    fi
}

scxctl_session_systray() {
    # Display a notification
    if [[ ! -z "$SCHEDULER_COICE" ]] && [[ ! -z "$MODE_CHOICE" ]]; then
        kdialog --title "CPU scheduler and profile changed" --passivepopup "Set the CPU scheduler to \"$SCHEDULER_COICE\" and tuning profile to \"$MODE_CHOICE\"." 10
    fi
}

## Main Program

MenuEnable=True

if [[ "$XDG_SESSION_DESKTOP" == "KDE" ]]; then

    if command -v "/usr/bin/kdialog" &> /dev/null; then

        while [[ ${MenuEnable} == True ]];

        do

            ## Main menu
            kde_main_menu

            if [[ "${MAIN_MENU}" == "Scxctl" ]]; then

                ## CPU config menu
                kde_cpu_menu

                if [[ "${CPU_CONFIG_MENU}" == "Start" ]]; then

                    kde_scheduler_menu
                    cpu_sched_start
                    scxctl_session_systray

                elif [[ "${CPU_CONFIG_MENU}" == "Switch" ]]; then

                    kde_scheduler_menu
                    cpu_sched_switch
                    scxctl_session_systray

                elif [[ "${CPU_CONFIG_MENU}" == "Stop" ]]; then

                    scxctl stop

                fi

            elif [[ "${MAIN_MENU}" == "Pipewire" ]]; then

                ## Pipewire session config menu
                kde_pipewire_session
                pw_session_logic
                pw_session_systray

            elif [[ "${MAIN_MENU}" == "Exit" ]]; then

                MenuEnable=False

            fi

        done

    elif command -v "/usr/bin/zenity" &> /dev/null; then

        while [[ ${MenuEnable} == True ]];

        do

            ## Main menu
            zenity_main_menu

            if [[ "${MAIN_MENU}" == "Scxctl" ]]; then

                ## CPU config menu
                zenity_cpu_menu

                if [[ "${CPU_CONFIG_MENU}" == "Start" ]]; then

                    zenity_scheduler_menu
                    cpu_sched_start
                    scxctl_session_systray

                elif [[ "${CPU_CONFIG_MENU}" == "Switch" ]]; then

                    zenity_scheduler_menu
                    cpu_sched_switch
                    scxctl_session_systray

                elif [[ "${CPU_CONFIG_MENU}" == "Stop" ]]; then

                    scxctl stop

                fi

            elif [[ "${MAIN_MENU}" == "Pipewire" ]]; then

                ## Pipewire session config menu
                zenity_pipewire_session
                pw_session_logic
                pw_session_systray

            elif [[ "${MAIN_MENU}" == "Exit" ]]; then

                MenuEnable=False

            fi

		done
        
    fi

else

    if command -v "/usr/bin/zenity" &> /dev/null; then

        while [[ ${MenuEnable} == True ]];

        do

            ## Main menu
            zenity_main_menu

            if [[ "${MAIN_MENU}" == "Scxctl" ]]; then

                ## CPU config menu
                zenity_cpu_menu

                if [[ "${CPU_CONFIG_MENU}" == "Start" ]]; then

                    zenity_scheduler_menu
                    cpu_sched_start
                    scxctl_session_systray

                elif [[ "${CPU_CONFIG_MENU}" == "Switch" ]]; then

                    zenity_scheduler_menu
                    cpu_sched_switch
                    scxctl_session_systray

                elif [[ "${CPU_CONFIG_MENU}" == "Stop" ]]; then

                    scxctl stop

                fi

            elif [[ "${MAIN_MENU}" == "Pipewire" ]]; then

                ## Pipewire session config menu
                zenity_pipewire_session
                pw_session_logic
                pw_session_systray

            elif [[ "${MAIN_MENU}" == "Exit" ]]; then

                MenuEnable=False

            fi

        done

    elif command -v "/usr/bin/kdialog" &> /dev/null; then

        while [[ ${MenuEnable} == True ]];

        do

            ## Main menu
            kde_main_menu

            if [[ "${MAIN_MENU}" == "Scxctl" ]]; then

                ## CPU config menu
                kde_cpu_menu

                if [[ "${CPU_CONFIG_MENU}" == "Start" ]]; then

                    kde_scheduler_menu
                    cpu_sched_start
                    scxctl_session_systray

                elif [[ "${CPU_CONFIG_MENU}" == "Switch" ]]; then

                    kde_scheduler_menu
                    cpu_sched_switch
                    scxctl_session_systray

                elif [[ "${CPU_CONFIG_MENU}" == "Stop" ]]; then

                    scxctl stop

                fi

            elif [[ "${MAIN_MENU}" == "Pipewire" ]]; then

                ## Pipewire session config menu
                kde_pipewire_session
                pw_session_logic
                pw_session_systray

            elif [[ "${MAIN_MENU}" == "Exit" ]]; then

                MenuEnable=False

            fi

        done
        
    fi

fi
